#!/usr/bin/python
import os, sys, imp

try:
   sys.path.insert(0, os.path.dirname(__file__) or '.')
   PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")
   virtenv = PY_DIR + '/virtenv/'

   PY_CACHE = os.path.join(virtenv, 'lib', os.environ['OPENSHIFT_PYTHON_VERSION'], 'site-packages')

   os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
   os.environ['DJANGO_SETTINGS_MODULE'] = 'mainapp.settings'
   sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'mainapp'))

   zvirtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'],
                           'virtenv', 'bin', 'activate_this.py')
   exec(compile(open(zvirtenv).read(), zvirtenv, 'exec'),
        dict(__file__ = zvirtenv) )
except IOError:
   pass

from run import application
